apiVersion: qlik.com/v1
kind: SelectivePatch
metadata:
  name: identity-providers-component-secrets
enabled: true
patches:
- target:
    kind: SuperSecret
  patch: |-
    apiVersion: qlik.com/v1
    kind: SuperSecret
    metadata:
      name: identity-providers-secrets
    stringData:
      tokenAuthPrivateKeyId: (( (ds "data").kid ))
      tokenAuthPrivateKey: |
        ((- "\n"))(( (ds "data").private_key | indent 8 ))
      idpConfigs: |-
        [ {
            "claimsMapping": {
              "name": "name",
              "sub": [
                  "sub",
                  "client_id"
              ]
            },
            "clientId": "foo",
            "clientSecret": "bar",
            "hostname": "elastic.example",
            "issuerConfig": {
              "authorization_endpoint": "http://elastic.example:32123/auth",
              "end_session_endpoint": "http://elastic.example:32123/session/end",
              "introspection_endpoint": "http://elastic.example:32123/token/introspection",
              "issuer": "http://simple-oidc-provider",
              "jwks_uri": "http://elastic.example:32123/certs",
              "token_endpoint": "http://elastic.example:32123/token",
              "userinfo_endpoint": "http://elastic.example:32123/me"
            },
            "postLogoutRedirectUri": "http://elastic.example",
            "realm": "simple"
          }
        ]
- target:
    kind: Secret
    name: identity-providers-secrets
  patch: |-
    - op: add
      path: /stringData
      value:
         mongodbUri: mongodb://$(PREFIX)-mongodb:27017/identity-providers