apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../../../base/vars
- ../../gke/configs
- ../../gke/secrets
- searchReplaceRealmName.yaml
- searchReplaceClientSecret.yaml
- searchReplaceDefaultUserPassword.yaml
- searchReplaceQlikIDPHost.yaml
- searchReplaceStaticIpName.yaml
transformers:
- ../transformers
