apiVersion: qlik.com/v1
kind: SearchReplace
metadata:
  name: component-ingress-staticIpName
  labels:
    key: staticIpName
target:
  kind: Ingress
path: metadata/annotations/kubernetes.io\/ingress.global-static-ip-name
search: \$\(STATIC_IP_NAME\)
replaceWithObjRef:
  objref:
    apiVersion: v1
    kind: ConfigMap
  fieldref:
    fieldpath: data.staticIpName
---
apiVersion: qlik.com/v1
kind: SearchReplace
metadata:
  name: component-managedCertificate-staticIpName
  labels:
    key: staticIpName
target:
  kind: ManagedCertificate
path: spec/domains
search: \$\(IDP_HOST_NAME\)
replaceWithObjRef:
  objref:
    apiVersion: v1
    kind: ConfigMap
  fieldref:
    fieldpath: data.staticIpName