apiVersion: qlik.com/v1
kind: SearchReplace
metadata:
  name: component-clientSecret
  labels:
    key: clientSecret
target:
  kind: SuperSecret
  name: keycloak-realm
path: stringData/realm.json
search: \$\(CLIENT_SECRET\)
replaceWithObjRef:
  objref:
    apiVersion: qlik.com/v1
    kind: SuperSecret
    name: keycloak-secrets
  fieldref:
    fieldpath: stringData.clientSecret