apiVersion: qlik.com/v1
kind: SearchReplace
metadata:
  name: component-ingress-idpHostName
  labels:
    key: idpHostName
target:
  kind: Ingress
path: spec/rules
search: \$\(IDP_HOST_NAME\)
replaceWithObjRef:
  objref:
    apiVersion: v1
    kind: ConfigMap
  fieldref:
    fieldpath: data.idpHostName
---
apiVersion: qlik.com/v1
kind: SearchReplace
metadata:
  name: component-managedCertificate-idpHostName
  labels:
    key: idpHostName
target:
  kind: ManagedCertificate
path: spec/domains
search: \$\(IDP_HOST_NAME\)
replaceWithObjRef:
  objref:
    apiVersion: v1
    kind: ConfigMap
  fieldref:
    fieldpath: data.idpHostName