apiVersion: qlik.com/v1
kind: SearchReplace
metadata:
  name: component-realmName
  labels:
    key: realmName
target:
  kind: SuperSecret
  name: keycloak-realm
path: stringData/realm.json
search: \$\(REALM_NAME\)
replaceWithObjRef:
  objref:
    apiVersion: qlik.com/v1
    kind: SuperConfigMap
    name: keycloak-configs
  fieldref:
    fieldpath: data.realmName
