apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app: reload-tasks
resources:
- ../../../transformers
transformers:
- ../../../../../.operator/transformers
- ../../../../../configuration/transformers
#Disable all transformers except these
patches:
- target:
    labelSelector: >-
      key notin (
        imageRegistry,
        ingressClass,
        ingressAuthUrl,
        keysUri,
        mongodbUri,
        qixDataReloadUri,
        chronosUri,
        natsStreamingClusterId,
        caCertificates
        )
  patch: |-
    - op: replace
      path: /enabled
      value: false
    - op: replace
      path: /default
      value: true