apiVersion: qlik.com/v1
kind: SearchReplace
metadata:
  name: idpHostName
target:
  kind: SearchReplace
  labelSelector: key=idpHostName
path: replace
search: \$\(IDP_HOST_NAME\)
replaceWithObjRef:
  objref:
    apiVersion: qlik.com/v1
    kind: SuperConfigMap
    name: gke-configs
  fieldref:
    fieldpath: data.idpHostName