apiVersion: qlik.com/v1
kind: SelectivePatch
metadata:
  name: idpHostName
  labels:
    key: idpHostName
enabled: true
patches:
- target:
    kind: SearchReplace
    labelSelector: key=idpHostName
  patch: |-
    apiVersion: qlik.com/v1
    kind: SearchReplace
    metadata:
      name: idpHostName
    replaceWithObjRef: null
    replace: $(IDP_HOST_NAME)