apiVersion: qlik.com/v1
kind: SearchReplace
metadata:
  name: component-nfsPath
  labels:
    key: nfsPath
target:
  kind: Deployment
path: spec/template/spec/volumes
search: \$\(NFS_PATH\)
replaceWithObjRef:
  objref:
    apiVersion: v1
    kind: ConfigMap
  fieldref:
    fieldpath: data.nfsPath
