apiVersion: qlik.com/v1
kind: SearchReplace
metadata:
  name: component-nfsServer
  labels:
    key: nfsServer
target:
  kind: Deployment
path: spec/template/spec/volumes
search: \$\(NFS_SERVER\)
replaceWithObjRef:
  objref:
    apiVersion: v1
    kind: ConfigMap
  fieldref:
    fieldpath: data.nfsServer
