apiVersion: qlik.com/v1
kind: SelectivePatch
metadata:
  name: redisPassword
  labels:
    key: redisPassword
enabled: true
patches:
- target:
    kind: Deployment
  patch: |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: component
    spec:
      template:
        spec:
          containers:
          - name: main
            env:
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: redisPassword
                  name: secrets
- target:
    kind: Deployment
    name: .*redis-slave
  patch: |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: redis-slave
    spec:
      template:
        spec:
          containers:
          - name: main
            env:
            - name: REDIS_MASTER_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: redisPassword
                  name: secrets
- target:
    kind: StatefulSet
  patch: |-
    apiVersion: apps/v1
    kind: StatefulSet
    metadata:
      name: component
    spec:
      template:
        spec:
          containers:
          - name: main
            env:
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: redisPassword
                  name: secrets
- target:
    kind: Secret
    name: .*-secrets
  patch: |-
    apiVersion: v1
    kind: Secret
    metadata:
      name: component-secrets
#    stringData:
#      redisPassword: null
