apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app: nfs-client-provisioner
generators:
  - generators
transformers:
  - patches
  - configs
  - transformers
  - ../../../../.operator/patches
  - ../../../../configuration/patches
  - ../../../base/transformers/release
  - vars
  - ../../../base/transformers/msgprefix
  - ../../../base/transformers/prefix
  - ../../../base/transformers/namespace
# images:
#   - name: quay.io/external_storage/nfs-client-provisioner
#     newName: $(IMAGE_REGISTRY)/nfs-client-provisioner