apiVersion: qlik.com/v1
kind: SelectivePatch
metadata:
  name: mongodbUri
  labels:
    key: mongodbUri
enabled: true
patches:
- target:
    kind: Deployment
  patch: |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: component
    spec:
      template:
        spec:
          containers:
          - name: main
            env:
            - name: MONGODB_URI
              valueFrom:
                secretKeyRef:
                  key: mongodbUri
                  name: secrets
- target:
    kind: Deployment
  patch: |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: component
    spec:
      template:
        spec:
          volumes:
          - name: qliksense-secrets
            secret:
              secretName: secrets
          containers:
          - name: main
            volumeMounts:
            - mountPath: /run/secrets/qlik.com/qliksense
              name: qliksense-secrets
              readOnly: true
            env:
            - $patch: delete
              name: MONGODB_URI_FILE
            - name: MONGODB_URI_FILE
              value: /run/secrets/qlik.com/qliksense/mongodbUri
- target:
    kind: CronJob
  patch: |-
    apiVersion: batch/v1beta1
    kind: CronJob
    metadata:
      name: component
    spec:
      jobTemplate:
        spec:
          template:
            spec:
              containers:
              - name: main
                env:
                - name: MONGODB_URI
                  valueFrom:
                    secretKeyRef:
                      key: mongodbUri
                      name: secrets
- target:
    kind: CronJob
  patch: |-
    apiVersion: batch/v1beta1
    kind: CronJob
    metadata:
      name: component
    spec:
      jobTemplate:
        spec:
          template:
            spec:
              volumes:
              - name: qliksense-secrets
                secret:
                  secretName: secrets
              containers:
              - name: main
                volumeMounts:
                - mountPath: /run/secrets/qlik.com/qliksense
                  name: qliksense-secrets
                  readOnly: true
                env:
                - $patch: delete
                  name: MONGODB_URI_FILE
                - name: MONGODB_URI_FILE
                  value: /run/secrets/qlik.com/qliksense/mongodbUri
- target:
    kind: Secret
    name: .*-secrets
  patch: |-
    - op: add
      path: stringData/mongodbUri
      value: null
    - op: remove
      path: stringData/mongodbUri
defaults:
- target:
    kind: Secret
    name: .*-secrets
  patch: |-
    - op: add
      path: stringData/mongodbUri
      value: null
    - op: remove
      path: stringData/mongodbUri
