apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app: elastic-infra
resources:
  - ../../../base/resources/elastic-infra/resources
generators:
  - generators
transformers:
  - patches
  - ../../../base/resources/elastic-infra/add-prefix
  - configs
  - ../../../base/resources/elastic-infra/transformers
  - ../../../../.operator/patches
  - ../../../../configuration/patches
  - ../../../base/transformers/release
  - ../../../base/resources/elastic-infra/vars
  - vars
  - ../../../base/transformers/msgprefix
  - ../../../base/transformers/prefix
  - ../../../base/transformers/namespace
images:
- name: qlik-docker-qsefe.bintray.io/nginx-ingress-controller
  newName: $(IMAGE_REGISTRY)/nginx-ingress-controller
configurations:
  - ../../../base/namereference.yaml
