apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app: engine
resources:
  - ../configs
  #- ../../../secrets
  - ../transformers
  #- ../../qliksense/generators/secrets
  #- ../../qliksense/generators/configs
  - ../../../../../.operator/patches
  - ../../../../../configuration/patches
  - ../../../transformers/release
  - ../vars
  - ../../../transformers/msgprefix
  - ../../../transformers/prefix
  - ../../../transformers/namespace
transformers:
  - selectivepatch.yaml
  - ../secrets
patches:
- target:
    kind: SuperSecret
  patch: |-
    - op: replace
      path: /metadata/name
      value: engine-secrets