apiVersion: qlik.com/v1
kind: SelectivePatch
metadata:
  name: keycloak-generated-operator-secrets
enabled: true
patches:
- patch: |
    apiVersion: qlik.com/v1
    kind: SuperSecret
    metadata:
      name: keycloak-secrets
    stringData:
      defaultUserPassword: |-
        ((- "\n"))(( index (ds "data") "defaultUserPassword" | base64.Decode | indent 8 ))
  target:
    kind: SuperSecret
    labelSelector: app=keycloak
- patch: |
    apiVersion: qlik.com/v1
    kind: SuperSecret
    metadata:
      name: keycloak-secrets
    stringData:
      password: |-
        ((- "\n"))(( index (ds "data") "password" | base64.Decode | indent 8 ))
  target:
    kind: SuperSecret
    labelSelector: app=keycloak
