apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app: keycloak
resources:
- ../../../transformers
- ../../../../base/transformers
transformers:
- ../../../../../.operator/transformers
- ../../../../../configuration/transformers
#Disable all transformers except these
patches:
- target:
    labelSelector: >-
      key notin (
        imageRegistry,
        ingressAuthUrl,
        idpHostName,
        realmName,
        clientSecret,
        staticIpName
      )
  patch: |-
    - op: replace
      path: /enabled
      value: false
    - op: replace
      path: /default
      value: true
- target:
    labelSelector: key = ingressAuthUrl
  patch: |-
    - op: replace
      path: /enabled
      value: false
    - op: replace
      path: /default
      value: false