apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../../../base/vars
- ../../gke/configs
- ../../gke/secrets
- searchReplaceClientSecret.yaml
- searchReplaceQlikIDPHost.yaml
- searchReplaceQlikDomain.yaml
- searchReplaceRealmName.yaml
transformers:
  - ../transformers