apiVersion: qlik.com/v1
kind: SearchReplace
metadata:
  name: component-qlikSenseDomain
  labels:
    key: qlikSenseDomain
target:
  kind: SuperSecret
  name: identity-providers-secrets
path: stringData/idpConfigs
search: \$\(QLIKSENSE_DOMAIN\)
replaceWithObjRef:
  objref:
    apiVersion: qlik.com/v1
    kind: SuperConfigMap
    name: identity-providers-configs
  fieldref:
    fieldpath: data.qlikSenseDomain