apiVersion: qlik.com/v1
kind: SearchReplace
metadata:
  name: component-idpHostName
  labels:
    key: idpHostName
target:
  kind: SuperSecret
  name: identity-providers-secrets
path: stringData/idpConfigs
search: \$\(IDP_HOST_NAME\)
replaceWithObjRef:
  objref:
    apiVersion: qlik.com/v1
    kind: SuperConfigMap
    name: identity-providers-configs
  fieldref:
    fieldpath: data.idpHostName