apiVersion: qlik.com/v1
kind: SearchReplace
metadata:
  name: component-clientSecret
  labels:
    key: clientSecret
target:
  kind: SuperSecret
  name: identity-providers-secrets
path: stringData/idpConfigs
search: \$\(CLIENT_SECRET\)
replaceWithObjRef:
  objref:
    apiVersion: qlik.com/v1
    kind: SuperSecret
    name: identity-providers-secrets
  fieldref:
    fieldpath: stringData.clientSecret
