apiVersion: qlik.com/v1
kind: SearchReplace
metadata:
  name: component-realmName
  labels:
    key: realmName
target:
  kind: SuperSecret
  name: identity-providers-secrets
path: stringData/idpConfigs
search: \$\(REALM_NAME\)
replaceWithObjRef:
  objref:
    apiVersion: qlik.com/v1
    kind: SuperConfigMap
    name: identity-providers-configs
  fieldref:
    fieldpath: data.realmName