apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app: dcaas-web
resources:
- ../../../transformers
transformers:
- ../../../../../.operator/transformers
- ../../../../../configuration/transformers
patches:
- target:
    labelSelector: >-
      key notin (
        imageRegistry,
        ingressClass,
        ingressAuthUrl
        )
  patch: |-
    - op: replace
      path: /enabled
      value: false
    - op: replace
      path: /default
      value: true