apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app: qliksense
generators:
  - generators
transformers:
  - transformers
  - ../../../base/transformers/release
  - ../../../base/transformers/prefix