apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app: keycloak
generators:
  - generators
resources:
  - managedCertificate.yaml
transformers:
  - ../secrets/transformers
  - ../configs/transformers
  - ../../../../../.operator/patches
  - ../../../../../configuration/patches
  - ../../../../base/transformers/release
  - ../../../../base/transformers/prefix
