apiVersion: qlik.com/v1
kind: SearchReplace
metadata:
  name: staticIpName
target:
  kind: SearchReplace
  labelSelector: key=staticIpName
path: replace
search: \$\(STATIC_IP_NAME\)
replaceWithObjRef:
  objref:
    apiVersion: qlik.com/v1
    kind: SuperConfigMap
    name: gke-configs
  fieldref:
    fieldpath: data.staticIpName