apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app: mongodb
resources:
  - helmchart.yaml
  - configs
  - secrets
transformers:
  - ../../../../../transformers
  - ../secrets
  - ../configs
  - values.yaml


