apiVersion: qlik.com/v1
kind: SearchReplace
metadata:
  name: realmName
target:
  kind: SearchReplace
  labelSelector: key=realmName
path: replace
search: \$\(REALM_NAME\)
replaceWithObjRef:
  objref:
    apiVersion: qlik.com/v1
    kind: SuperConfigMap
    name: gke-configs
  fieldref:
    fieldpath: data.realmName
