apiVersion: qlik.com/v1
kind: SelectivePatch
metadata:
  name: realmName
  labels:
    key: realmName
enabled: true
patches:
- target:
    kind: SearchReplace
    labelSelector: key=realmName
  patch: |-
    apiVersion: qlik.com/v1
    kind: SearchReplace
    metadata:
      name: realmName
    replaceWithObjRef: null
    replace: $(REALM_NAME)
