apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- selectivepatch.yaml
- searchReplacePrefix.yaml
- ../../../../../../.operator/secrets
- ../../../../../../configuration/secrets
