apiVersion: qlik.com/v1
kind: SearchReplace
metadata:
  name: keycloak-prefix
target:
  kind: SuperSecret
  name: keycloak-realm
path: prefix
search: \$\(PREFIX\)
replaceWithObjRef:
  objref:
    apiVersion: qlik.com/v1
    kind: SuperSecret
    name: keycloak-realm
  fieldref:
    fieldpath: metadata.labels.release
