apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app: keycloak
resources:
- helmchart.yaml
transformers:
- ../../../../../base/transformers/release
- ../../../../transformers
- searchReplacePrefix.yaml


