apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app: certificate
resources:
  - resources
generators:
  - generators
transformers:
  - configs
  - transformers
  - ../../../../.operator/patches
  - ../../../../configuration/patches
  - ../../../base/transformers/release
  - vars
  - ../../../base/transformers/msgprefix
  - ../../../base/transformers/prefix
