apiVersion: qlik.com/v1
kind: SearchReplace
metadata:
  name: qlikSenseDomain
target:
  kind: SearchReplace
  labelSelector: key=qlikSenseDomain
path: replace
search: \$\(QLIKSENSE_DOMAIN\)
replaceWithObjRef:
  objref:
    apiVersion: qlik.com/v1
    kind: SuperConfigMap
    name: gke-configs
  fieldref:
    fieldpath: data.qlikSenseDomain