apiVersion: qlik.com/v1
kind: SearchReplace
metadata:
  name: change-tls-elastic-infra-tls-secret
target:
  kind: Deployment
path: spec/template/spec/containers/args
search: --default-ssl-certificate=\$\(NAMESPACE\)\/\$\(PREFIX\)-elastic-infra-tls-secret
replace: --default-ssl-certificate=$(NAMESPACE)/$(PREFIX)-tls