apiVersion: qlik.com/v1
kind: SearchReplace
metadata:
  name: clientSecret
target:
  kind: SearchReplace
  labelSelector: key=clientSecret
path: replace
search: \$\(CLIENT_SECRET\)
replaceWithObjRef:
  objref:
    apiVersion: qlik.com/v1
    kind: SuperSecret
    name: gke-secrets
  fieldref:
    fieldpath: stringData.clientSecret