apiVersion: qlik.com/v1
kind: SelectivePatch
metadata:
  name: clientSecret
  labels:
    key: clientSecret
enabled: true
patches:
- target:
    kind: SearchReplace
    labelSelector: key=clientSecret
  patch: |-
    apiVersion: qlik.com/v1
    kind: SuperSecret
    metadata:
      name: clientSecret
    replaceWithObjRef: null
    replace: $(CLIENT_SECRET)
