apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app: data-connector-qwc
resources:
- ../../../../configs
transformers:
- ../../configs
patches:
- target:
    kind: SuperConfigMap
  patch: |-
    - op: replace
      path: /metadata/name
      value: data-connector-qwc-configs