apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app: identity-providers
resources:
  - ../../../base/resources/identity-providers/resources
generators:
  - generators
transformers:
  - secrets/transformers
  - configs/transformers
  - transformers
  - ../../../../.operator/patches
  - ../../../../configuration/patches
  - ../../../base/transformers/release
  - vars
  - ../../../base/transformers/msgprefix
  - ../../../base/transformers/prefix
  - ../../../base/transformers/namespace
images:
  - name: qlik-docker-qsefe.bintray.io/identity-providers
    newName: $(IMAGE_REGISTRY)/identity-providers
