apiVersion: qlik.com/v1
kind: SearchReplace
metadata:
  name: prefix
target:
  labelSelector: release
path: /
search: \$\(PREFIX\)
replaceWithObjRef:
  objref:
    apiVersion: qlik.com/v1
    kind: PrefixSuffixTransformer
    name: new-release
  fieldref:
    fieldpath: metadata.labels.release