apiVersion: v1
data:
  jwtPrivateKey: IA==
  redisUserStatePassword: ""
  redisUserStateSentinelPassword: ""
kind: Secret
metadata:
  name: engine-secrets
type: Opaque
---
apiVersion: v1
data:
  jwtPrivateKey: IA==
kind: Secret
metadata:
  name: engine-service-jwt-secret
type: Opaque
---
