apiVersion: qlik.com/v1
kind: SearchReplace
metadata:
  name: imageRegistry
target:
  kind: SearchReplace
  labelSelector: key=imageRegistry
path: replace
search: \$\(IMAGE_REGISTRY\)
replaceWithObjRef:
  objref:
    apiVersion: qlik.com/v1
    kind: SuperConfigMap
    name: configs
  fieldref:
    fieldpath: data.imageRegistry